import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('production'),
  PORT: z.coerce.number().int().positive().default(3000),
  PUBLIC_ASSET_BASE_URL: z.string().url(),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  TOTEM_WORKER_CONCURRENCY: z.coerce.number().int().positive().max(500).default(50),
  STRIPE_SECRET_KEY: z.string().min(1),
  STRIPE_WEBHOOK_SECRET: z.string().min(1),
  TOTEM_TEXT_API_URL: z.string().url(),
  TOTEM_IMAGE_API_URL: z.string().url(),
  TOTEM_AUDIO_API_URL: z.string().url(),
  TOTEM_PDF_API_URL: z.string().url(),
  TOTEM_MICROSERVICE_API_KEY: z.string().min(1),
  CHECKOUT_SUCCESS_URL: z.string().url(),
  CHECKOUT_CANCEL_URL: z.string().url(),
  TOTEM_PRICE_ORIGINE_CENTS: z.coerce.number().int().positive(),
  TOTEM_PRICE_ANCESTRAL_CENTS: z.coerce.number().int().positive(),
  TOTEM_PRICE_FAMILLE_CENTS: z.coerce.number().int().positive(),
  SUPABASE_URL: z.string().url(),
  SUPABASE_ANON_KEY: z.string().min(1),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
  SUPABASE_STORAGE_BUCKET: z.string().min(1),
  DELIVERY_SIGNING_SECRET: z.string().min(32),
  RESEND_API_KEY: z.string().min(1),
  RESEND_SENDER_EMAIL: z.string().email(),
  RESEND_SENDER_NAME: z.string().min(1),
  ALERT_EMAIL: z.string().email(),
  CORS_ORIGIN: z.string().optional(),
});
