import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('production'),
  PORT: z.coerce.number().int().positive().default(3000),
  PUBLIC_ASSET_BASE_URL: z.string().url(),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  TOTEM_WORKER_CONCURRENCY: z.coerce.number().int().positive().max(500).default(50),
  STRIPE_SECRET_KEY: z.string().min(1),
  STRIPE_WEBHOOK_SECRET: z.string().min(1),
  TOTEM_TEXT_API_URL: z.string().url(),
  TOTEM_IMAGE_API_URL: z.string().url(),
  TOTEM_AUDIO_API_URL: z.string().url(),
  TOTEM_PDF_API_URL: z.string().url(),
  TOTEM_MICROSERVICE_API_KEY: z.string().min(1),
  R2_ENDPOINT: z.string().url(),
  R2_ACCESS_KEY_ID: z.string().min(1),
  R2_SECRET_ACCESS_KEY: z.string().min(1),
  R2_BUCKET: z.string().min(1),
  R2_SIGNING_SECRET: z.string().min(32),
  BREVO_API_KEY: z.string().min(1),
  BREVO_SENDER_EMAIL: z.string().email(),
  BREVO_SENDER_NAME: z.string().min(1),
  BREVO_TEMPLATE_DELIVERY_ID: z.coerce.number().int().positive(),
  BREVO_TEMPLATE_ALERT_ID: z.coerce.number().int().positive(),
  ALERT_EMAIL: z.string().email(),
});
